#%RAML 1.0 DataType
type: object
properties:
  productId: integer
  name: string
  description: string
  original price: integer
  # offer: string
  # offerPrice: integer
  # offerValidUntil: integer
  brandName: string
  image1: string
  image2: string
  image3: string



  
  

  
 